os:
  - osx
  - linux
  - windows
language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker-compose --version;
    fi
script:
  - npm ci
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        npm run test;
    fi
  - npm run build
  - npm run electron-dist
deploy:
  provider: releases
  github-token: $GH_TOKEN
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true
