os:
  - osx
  - linux
  - windows
language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker-compose --version; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker-compose run builder npm ci;
    else
      npm ci;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm run test; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm run build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --volume $(pwd):/usr/app --workdir /usr/app cpapazaf/scytale_win_builder:1 npm run electron-dist;
      docker run --volume $(pwd):/usr/app --workdir /usr/app cpapazaf/scytale_win_builder:1 npm run electron-dist-win;
    else
      npm run electron-dist;
    fi
deploy:
  provider: releases
  github-token: $GH_TOKEN
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true
