os:
- osx
- linux
addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm ci
- npm run build
- npm run electron-dist
deploy:
  provider: releases
  github-token: $GH_TOKEN
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true
